require_relative '../associations/book'
require_relative '../classes/person'
require_relative '../associations/classroom'
require_relative '../classes/student'
require_relative '../associations/rental'
require_relative '../classes/teacher'
